### ISSUE TITLE
当父View释放时，当前视图因为被Timer强引用而不能释放,timer也未释放掉

### ISSUE THREAD

**Issue by bluesky0109** [snsogbl/CustomPhotosBrowse#1]
当父View释放时，当前视图因为被Timer强引用而不能释放,timer也未释放掉

**Comment by bluesky0109** [comment]
将CustomPhotosBrowse放到navigation管理的controller中 pop时即可模拟到现象 timer调用的方法还在一直跑

**Comment by snsogbl** [comment]
已解决
